### ISSUE TITLE
Do i need a redirect URL?

### ISSUE THREAD

**Issue by aalfaiate** [tmunzer/identity#9]
I am having an issue with a GET request in Postman. I have configured mailer_config.js and config.js to match my credentials. My headers in postman are also correct other than for X-AH-API-CLIENT-REDIRECT-URI which I am unsure of what the value should be if even needed. Can you access me on what I am doing wrong? Receiving a 404 error.

**Comment by tmunzer** [comment]
Hi @aalfaiate ,
You should not have to use Postman with this application. if you have question about aerohive APIs, the best way to get answers is to use the Developer Portal Alias <Developer.Portal@aerohive.com>

Anyway, the "X-AH-API-CLIENT-REDIRECT-URI" has to be the same value as what you configured in your developer portal account (https://developer.aerohive.com/)

**Comment by aalfaiate** [comment]
Okay thanks for that, makes sense. Not using Postman now, when running www (nodemon www), it says "Listening on port 3000", but getting an error with the hostname. Should the hostname be "localhost" or the URL of HiveManager when logged in? And also should my port be 3000?

**Comment by tmunzer** [comment]
the redirect-url is the url where your app is reachable (not HiveManager).
So, if you are running the App on your laptop directly, the redirect-url will be something like "https://localhost:3000/oauth/reg".

Please not that the redirect-url MUST use HTTPS. So the app has to manage HTTPS too.

**Comment by tmunzer** [comment]
no update
